library(RoughSets)
data("RoughSetData")
hiring.decision<-RoughSetData$hiring.dt
hiring.Shuffled <- hiring.decision[sample(nrow(hiring.decision)),]
hdx <- round(0.7 * nrow(hiring.Shuffled))
hire.tra <-SF.asDecisionTable(hiring.Shuffled[1:hdx,],decision.attr = 5, indx.nominal = 5)
hire.test <- SF.asDecisionTable(hiring.Shuffled[(hdx+1):nrow(hiring.Shuffled), -ncol(hiring.Shuffled)])

## FEATURE SELECTION without computation of approximations, the two reducts that is
# Hire.table and Hire.table_2 contain the same attributes
hire.rst <- FS.feature.subset.computation(hire.tra,method="greedy.heuristic.superreduct")
hire.table <- SF.applyDecTable(hire.tra, hire.rst)

hire.rst_2 <- FS.feature.subset.computation(hire.tra,method = "quickreduct.rst")
hire.table_2 <- SF.applyDecTable(hire.tra, hire.rst_2)

# Rule generation, only three rules based 
rules_1 <- RI.indiscernibilityBasedRules.RST(hire.tra,hire.rst)
rules_1

## With calculations of approximations, gives me 3 reducts####
IND <- BC.IND.relation.RST(hire.tra, feature.set = NULL)

roughset <- BC.LU.approximation.RST(hire.tra, IND)
region.RST <- BC.positive.reg.RST(hire.tra, roughset)

disc.mat <- BC.discernibility.mat.RST(hire.tra, range.object = NULL)

decision_table_hiring <- FS.all.reducts.computation(disc.mat)

# Using the greedy heuristic method..not seeing it being optimal for this problem, the table is same as hire.table only difference is the data( 6 for splitting) and  (8 without splitting)

greedy_hiring_table <- FS.greedy.heuristic.reduct.RST(hiring.decision, qualityF = X.entropy,epsilon = 0.9)
GHS_Hiring <- SF.applyDecTable(hiring.decision,greedy_hiring_table)

# reduct 1 is the same as the first reduct generated by either greedy heursitic and quick reduct
hiring_Reduct1 <- SF.applyDecTable(hire.tra,decision_table_hiring,control = list(indx.reduct = 1))
hiring_Reduct1 <- SF.asDecisionTable(hiring_Reduct1,decision.attr = 2, indx.nominal = 2)
# Reduct 2
hiring_Reduct2 <- SF.applyDecTable(hire.tra,decision_table_hiring,control = list(indx.reduct = 2))
hiring_Reduct2 <- SF.asDecisionTable(hiring_Reduct2,decision.attr = 3, indx.nominal = 3)
# Reduct 3...This reduct doesnt make sense because it requires the qualifications and reference to get hired
hiring_Reduct3 <- SF.applyDecTable(hire.tra,decision_table_hiring,control = list(indx.reduct = 3))
hiring_Reduct3 <- SF.asDecisionTable(hiring_Reduct3,decision.attr = 3, indx.nominal = 3)

### Rule induction using Rough Set Using indiscernibility based  rules didnt work

hire.rule_1 <- RI.indiscernibilityBasedRules.RST(hiring_Reduct2,roughset)

hire.rule_2 <- RI.indiscernibilityBasedRules.RST(hiring.decision,roughset)


# AQ Rule generation. Gives 15 rules
rules.2 <- RI.AQRules.RST(hiring_Reduct2,confidence = 0.9, timesCovered = 3)

rules.3 <- RI.AQRules.RST(hiring_Reduct3,confidence = 0.9, timesCovered = 3) # The third reduct

rules.2
rules.3



####Using Association Rule Mining method....

data("RoughSetData")

attr <- c(1,2,3)

decision.table.hiring<-RoughSetData$hiring.dt

IND_ARM <- BC.IND.relation.RST(decision.table.hiring, feature.set = attr)

roughset_ARM <- BC.LU.approximation.RST(decision.table.hiring, IND_ARM)

region.RST_ARM <- BC.positive.reg.RST(decision.table.hiring, roughset_ARM)

disc.mat_ARM <- BC.discernibility.mat.RST(decision.table.hiring, range.object = NULL)

decision_table_hiring <- FS.all.reducts.computation(disc.mat)# Supposed to use greedy heuristic ethod

new_hiring_table2 <- SF.applyDecTable(decision.table.hiring,decision_table_hiring,control = list(indx.reduct = 2))

# Association rule mining method
library(arules)
library(tidyverse)
library(arulesViz)
library(knitr)
library(gridExtra)
library(lubridate)

ARM_hiring.decision<-RoughSetData$hiring.dt

ARM_hiring<- as.data.frame(ARM_hiring.decision )

hdata <- as(ARM_hiring,"transactions")

hdata

itemFrequencyPlot(hdata, topN=15, type="absolute", col="wheat2",xlab="Item name", ylab="Frequency (absolute)", main="Absolute Item Frequency Plot")

# Rules generated are 71 in total with supp set to 0.1 and confidence set to 0.9
rules <- apriori(hdata,parameter = list(minlen=2,supp=0.1,conf=0.9),appearance = list(rhs=c("Decision=Reject","Decision=Accept"),default="lhs"))
inspect(rules)

rules_df <- data.frame(DATAFRAME(rules, separate = TRUE, setStart = '', itemSep = ' + ', setEnd = ''))

rules_df

#Selecting only the top 10 rules according to support and confidence









# Generating Using the greedy heuristic method, only one attribute experience, have to check on this
decision_hiring_GH_1<- FS.greedy.heuristic.reduct.RST(decision.table.hiring,qualityF = X.entropy,epsilon = 0.9)

decision_greedy <- FS.feature.subset.computation(hire.tra,method="greedy.heuristic.superreduct")


decision_hiring <- FS.greedy.heuristic.reduct.RST(decision.table,qualityF = X.entropy,epsilon = 0.9)



