library(RoughSets)
data("RoughSetData")
attr <- c(1,2,3)
IND <- BC.IND.relation.RST(decision.table, feature.set = attr.P)
decision.table<-RoughSetData$hiring.dt
IND <- BC.IND.relation.RST(decision.table, feature.set = attr.P)
IND <- BC.IND.relation.RST(decision.table, feature.set = attr)
roughset <- BC.LU.approximation.RST(decision.table, IND)
region.RST <- BC.positive.reg.RST(decision.table, roughset)
disc.mat <- BC.discernibility.mat.RST(decision.table, range.object = NULL)
decision_table_hiring <- FS.all.reducts.computation(disc.mat)
new_hiring_table <- SF.applyDecTable(decision.table,decision_table_hiring,control = list(indx.reduct = 1))
install.packages("arules")
library(arules)
library(arules)
AR_table <- as.data.frame(new_hiring_table )
View(AR_table)
tdata <- as(AR_table,"transactions")
View(tdata)
rules <- apriori(tdata,parameter = list(minlen=2,supp=0.005,conf=0.8),appearance = list(rhs=c("Decision=Reject","Decision=Accept"),default="lhs",control=list(verbose=F)))
rules <- apriori(tdata,parameter = list(minlen=2,supp=0.005,conf=0.8),appearance = list(rhs=c("Decision=Reject","Decision=Accept"),default="lhs"))
inspect(rules)
rules_df <- data.frame(lhs=labels(lhs(rules)),rhs=labels(rhs(rules)))
View(rules_df)
rules_df <- data.frame(lhs=labels(lhs(rules)),rhs=labels(rhs(rules)),rules@quality)
